apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"2110-character","namespace":"default"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"2110-character-app"}},"template":{"metadata":{"labels":{"app":"2110-character-app"}},"spec":{"containers":[{"image":"stephenesu/2110-character:latest","name":"2110-character","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2025-03-14T10:16:05Z"
  generation: 3
  name: 2110-character
  namespace: default
  resourceVersion: "452514"
  uid: 2bb8cf3e-d08e-4b6a-a639-4b3a6e666278
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: 2110-character-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 2110-character-app
    spec:
      containers:
      - image: stephenesu/2110-character:latest
        imagePullPolicy: Always
        name: 2110-character
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-03-14T10:16:05Z"
    lastUpdateTime: "2025-03-14T10:16:58Z"
    message: ReplicaSet "2110-character-6b54bc7f77" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-25T08:15:28Z"
    lastUpdateTime: "2025-03-25T08:15:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
