apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"character-service","namespace":"default"},"spec":{"ports":[{"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"2110-character-app"},"type":"LoadBalancer"}}
    metallb.universe.tf/ip-allocated-from-pool: default-pool
  creationTimestamp: "2025-03-13T14:03:25Z"
  name: character-service
  namespace: default
  resourceVersion: "320065"
  uid: cb53ee9e-0728-4f24-9fc3-aea8878d2ec8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.116.55
  clusterIPs:
  - 10.96.116.55
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30258
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: 2110-character-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.63.206
      ipMode: VIP
