apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"583-festava-app"},"name":"583-festava","namespace":"default"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"583-festava"}},"template":{"metadata":{"labels":{"app":"583-festava"}},"spec":{"containers":[{"image":"stephenesu/583-festava:latest","name":"583-festava","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/app/data","name":"583-festava-storage"}]}],"volumes":[{"name":"583-festava-storage","persistentVolumeClaim":{"claimName":"583-festava-pvc"}}]}}}}
  creationTimestamp: "2025-03-17T13:57:48Z"
  generation: 1
  labels:
    app: 583-festava-app
  name: 583-festava
  namespace: default
  resourceVersion: "452520"
  uid: e7325901-0157-491c-b1de-54fc9d46b9a1
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: 583-festava
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 583-festava
    spec:
      containers:
      - image: stephenesu/583-festava:latest
        imagePullPolicy: Always
        name: 583-festava
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/data
          name: 583-festava-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: 583-festava-storage
        persistentVolumeClaim:
          claimName: 583-festava-pvc
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2025-03-17T14:24:27Z"
    lastUpdateTime: "2025-03-17T14:25:00Z"
    message: ReplicaSet "583-festava-7b4f954895" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-25T08:15:28Z"
    lastUpdateTime: "2025-03-25T08:15:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
