apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"festava-583-service","namespace":"default"},"spec":{"ports":[{"port":9000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"583-festava"},"type":"LoadBalancer"}}
    metallb.universe.tf/ip-allocated-from-pool: default-pool
  creationTimestamp: "2025-03-17T14:01:42Z"
  name: festava-583-service
  namespace: default
  resourceVersion: "393396"
  uid: 85218934-5418-4b39-8f7f-5a56d293d434
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.187.210
  clusterIPs:
  - 10.107.187.210
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31844
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: 583-festava
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.63.207
      ipMode: VIP
