---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: templatemo-378-dragonfly-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data
