---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: templatemo-378-dragonfly-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
