---
apiVersion: v1
kind: Service
metadata:
  name: templatemo-378-dragonfly-service
  labels:
    app: templatemo-378-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: templatemo-378-app
