apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: default-pool
  creationTimestamp: "2025-03-04T15:43:08Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v3.2.1
    helm.sh/chart: prometheus-27.5.1
  name: prometheus-service
  namespace: default
  resourceVersion: "197351"
  uid: 4c99d7ca-f82b-4d56-9394-6c6e7ebf960a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.91.10
  clusterIPs:
  - 10.109.91.10
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-1
    nodePort: 32565
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    nodePort: 32438
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.63.203
      ipMode: VIP
